trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 8.x
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'NuGet Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: 'src/NuGet.Config'

  - task: DotNetCoreCLI@2
    displayName: 'Run Build'
    inputs:
      command: build
      projects: '**/*.csproj'